### ISSUE TITLE
TypeError on router

### ISSUE THREAD

**Issue by sestegra** [gopherjs/todomvc#3]
**Environment**
- Go 1.5 Windows 32
- gopherjs 67b6a97
- todomvc 97fbbf3
- Chrome 45.0.2454.85 m

**Scenario**
- Compile app.go with gopherjs build app.go
- Serve files
- Load app.html into Chrome
- Type error occured on console
Uncaught TypeError: r.Object.on is not a function
  $packages.github.com/gopherjs/todomvc/utils.Router.ptr.On @ utils.go:82
  $packages.main.App.ptr.initRouter @ app.go:82
  $packages.main.main @ app.go:21
  $packages.main.$init @ app.js:38015
  $goroutine @ app.js:1419
  $schedule @ app.js:1473
  $go @ app.js:1449
  (anonymous function) @ app.js:38025
  (anonymous function) @ app.js:38028

**Comment by rusco** [comment]
There have been major changes in gopherjs meanwhile. I will try to create a slimmer/striped down version of this issue for better investigation.

**Comment by rusco** [comment]
Hi, 
could you check again with current GopherJS Trunk ? Apparently it works again.
